# Ruff configuration

select = ["E", "F", "B", "I", "UP", "C90", "SIM"]
ignore = ["E501", "B008"]  # Line too long & function call as default arg

target-version = "py311"
line-length = 100

exclude = [
    ".venv",
    "build",
    "dist",
    "__pycache__",
    ".mypy_cache",
    ".ruff_cache",
    ".git",
    ".tox",
]

[format]
quote-style = "double"
skip-magic-trailing-comma = false
indent-style = "space"
line-ending = "lf"

[isort]
known-first-party = ["src"]
combine-as-imports = true
force-single-line = false