apiVersion: v1
kind: Service
metadata:
  name: iris-service
spec:
  selector:
    app: iris  # matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80            # external port
      targetPort: 5000    # internal container port
  type: NodePort          # exposes the service on a port of the node
